# On utilise Nginx pour servir le site statique
FROM nginx:alpine

# ATTENTION : Il y a une espace après le premier point !
COPY . /usr/share/nginx/html

# Le port par défaut de Nginx est le 80
EXPOSE 80